/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminExperienceRouteImport } from './routes/admin/experience'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSkillsRouteImport } from './routes/admin/skills'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as AdminCvsIndexRouteImport } from './routes/admin/cvs/index'
import { Route as AdminCvsIdRouteImport } from './routes/admin/cvs/$id'
import { Route as OgProjectsFileRouteImport } from './routes/og/projects.$file'
import { Route as ApiCvSlugPdfRouteImport } from './routes/api/cv.$slug.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExperienceRoute = AdminExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCvsIndexRoute = AdminCvsIndexRouteImport.update({
  id: '/cvs/',
  path: '/cvs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCvsIdRoute = AdminCvsIdRouteImport.update({
  id: '/cvs/$id',
  path: '/cvs/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OgProjectsFileRoute = OgProjectsFileRouteImport.update({
  id: '/og/projects/$file',
  path: '/og/projects/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvSlugPdfRoute = ApiCvSlugPdfRouteImport.update({
  id: '/api/cv/$slug/pdf',
  path: '/api/cv/$slug/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/cvs/$id': typeof AdminCvsIdRoute
  '/og/projects/$file': typeof OgProjectsFileRoute
  '/admin/cvs/': typeof AdminCvsIndexRoute
  '/api/cv/$slug/pdf': typeof ApiCvSlugPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/cvs/$id': typeof AdminCvsIdRoute
  '/og/projects/$file': typeof OgProjectsFileRoute
  '/admin/cvs': typeof AdminCvsIndexRoute
  '/api/cv/$slug/pdf': typeof ApiCvSlugPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/cvs/$id': typeof AdminCvsIdRoute
  '/og/projects/$file': typeof OgProjectsFileRoute
  '/admin/cvs/': typeof AdminCvsIndexRoute
  '/api/cv/$slug/pdf': typeof ApiCvSlugPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/admin/experience'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/skills'
    | '/projects/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/projects/'
    | '/services/'
    | '/admin/cvs/$id'
    | '/og/projects/$file'
    | '/admin/cvs/'
    | '/api/cv/$slug/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/admin/experience'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/skills'
    | '/projects/$slug'
    | '/services/$slug'
    | '/admin'
    | '/projects'
    | '/services'
    | '/admin/cvs/$id'
    | '/og/projects/$file'
    | '/admin/cvs'
    | '/api/cv/$slug/pdf'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/admin/experience'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/skills'
    | '/projects/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/projects/'
    | '/services/'
    | '/admin/cvs/$id'
    | '/og/projects/$file'
    | '/admin/cvs/'
    | '/api/cv/$slug/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  OgProjectsFileRoute: typeof OgProjectsFileRoute
  ApiCvSlugPdfRoute: typeof ApiCvSlugPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/experience': {
      id: '/admin/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminExperienceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cvs/': {
      id: '/admin/cvs/'
      path: '/cvs'
      fullPath: '/admin/cvs/'
      preLoaderRoute: typeof AdminCvsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cvs/$id': {
      id: '/admin/cvs/$id'
      path: '/cvs/$id'
      fullPath: '/admin/cvs/$id'
      preLoaderRoute: typeof AdminCvsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/og/projects/$file': {
      id: '/og/projects/$file'
      path: '/og/projects/$file'
      fullPath: '/og/projects/$file'
      preLoaderRoute: typeof OgProjectsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv/$slug/pdf': {
      id: '/api/cv/$slug/pdf'
      path: '/api/cv/$slug/pdf'
      fullPath: '/api/cv/$slug/pdf'
      preLoaderRoute: typeof ApiCvSlugPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminExperienceRoute: typeof AdminExperienceRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCvsIdRoute: typeof AdminCvsIdRoute
  AdminCvsIndexRoute: typeof AdminCvsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminExperienceRoute: AdminExperienceRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCvsIdRoute: AdminCvsIdRoute,
  AdminCvsIndexRoute: AdminCvsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  OgProjectsFileRoute: OgProjectsFileRoute,
  ApiCvSlugPdfRoute: ApiCvSlugPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
